### PR TITLE
Add config override for the wysiwyg in microsites

### PR DESCRIPTION
**Pull request by msayoung**
Not sure if this is the best way to do it, but I've copied the config from localgov_media and put it in localgov_microsites profile. 

(it just removes H1 as an option in the wysiwyg)

### CODE REVIEW

**Comment by ekes** [comment]
We depend on localgov_media so we should get the config from localgov_media? We don't?

**Review by finnlewis — APPROVED** [review]
This works for me. @ekes if you think we need an issue to review where this config comes from, let's create one.

**Comment by ekes** [comment]
> This works for me. @ekes if you think we need an issue to review where this config comes from, let's create one

Sure. So the question is if localgov_media works in the localgov profile, why doesn't it work in the localgov_microsites profile?

I am correct here that we are just duplicating the _same_ configuration in two places for microsites?

**Comment by msayoung** [comment]
No @ekes - I'm changing it for microsites. sorry that wasn't clear

**Pull request merged**
