### PR TITLE
Add config for metatags

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
@finnlewis - this adds some default metatag configuration. I'm not sure if this is what you intended in your comment on this https://github.com/localgovdrupal/localgov_microsites/issues/266

**Comment by finnlewis** [comment]
Thanks @msayoung 

The defaults look like a good starting point.

However, I see the metatags in the source for the node on the control domain, but not on the node when viewed in the microsite. 
Is this working for you? Might we need some other magic to make it play with domain and group?

**Comment by msayoung** [comment]
@finnlewis could you check with a page that isn't the homepage please. It seems to be working with most pages, but not that one.

**Review by finnlewis — APPROVED** [review]
Yes, it works with other content! Maybe we need to re-roll the default content page with metatags after this is in?

**Pull request merged**
