### PR TITLE
Remove patch that is included in Drupal 9.5.1

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
@ekes points out that we have agreed that we support the currently supported versions of core.

If we remove the patch and require 9.5.1 or above, this will force anyone who want to stay on 9.4 to pin the profile. 

So maybe this is not the best way to proceed. 

We could just leave the patch there and allow composer to complain when the patch fails. 

We could start maintaining a branch for each minor branch of Drupal: 9.4 and 9.5 (an 10 when we're ready).

We'll probably want to think about this and discuss.

**Comment by stephen-cox** [comment]
It makes sense to do a minor release with Drupal 9.5 support while maintaining the current release with the patch and 9.4 support. There's not a lot in the profile so maintaining 2 releases for a while shouldn't add too much extra work.

We are still on a beta release, so how to maintain two release branches and what happens when we finally make a stable release will need agreeing.

**Comment by ekes** [comment]
I'm fine with both options: Keeping and allowing it to fail to patch, moan, but not stop; Or making a minor release. The latter is obviously cleaner if a smidge more work. As @finnlewis mentioned in slack "Thunder track a branch for each minor version it seems:"... then of course you'd _always_ be maintaining two (or three - when Drupal comes with an LTS version) versions, even when they're not technically required.

**Comment by finnlewis** [comment]
We could maintain 2.4.x for 9.4 and 2.5.x for 9.5, then 3.0.x for 10.0 etc. 

Would this suggest beta tags like 2.4.0-beta2 and 2.5.0-beta2 ?

**Comment by finnlewis** [comment]
So.... 

we'll want to create branches

2.0.x (for Drupal up to 9.4)
2.1.x (for Drupal 9.5 and up)

and release branches: 

realease-2.0.x
realease-2.1.x

remake this pull request against the 2.1.x branch

new release tag: 
2.1.0-beta1 (for 

new pull request to the 2.0.x branch to restrict Drupal core to 9.4
tag this release to 2.0.0-beta2

update default branch in GitHub to 2.1.x

**Comment by finnlewis** [comment]
From our discussion in Merge Monday, moved this pull request to the 2.1.x branch which will support Drupal 9.5 and up. 

Could I get an approval @ekes / @stephen-cox ?

**Review by stephen-cox — APPROVED** [review]
Removed the core patch and install Drupal 9.5 as expected.

**Pull request merged**
