### PR TITLE
Added default node 1

### LINKED ISSUE #67: Define and implement the default page content (headings and components)
@stephen-cox to create demo sites

@markconroy  / @richard-s-rowley to create a page with headings and content

@ekes to wrap this up into the default page when a microsite gets created

(Note long term we might want to clone a node)

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #67

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Tested locally, and the node is full of paragraphs and images! :)

**Comment by stephen-cox** [comment]
Content installs correctly but you can't edit any paragraph items. Error thrown via Ajax is

```
TypeError: Drupal\Core\Field\WidgetBase::errorElement(): Argument #1 ($element) must be of type array, null given, called in /app/web/core/lib/Drupal/Core/Field/WidgetBase.php on line 474 in Drupal\Core\Field\WidgetBase->errorElement() (line 540 of /app/web/core/lib/Drupal/Core/Field/WidgetBase.php).
```

**Comment by stephen-cox** [comment]
@ekes This should be working now

**Review by ekes — APPROVED** [review]
Confirmed now installs with node/1 and the paragraphs are editable.

**Pull request merged**
