### PR TITLE
Feature/84 layout paragraphs 2

### PR DESCRIPTION
**Pull request by finnlewis**
This pull request switches branches on localgov_subsites and localgov_page to use Layout Paragraphs 2.x

The UX is much better and I'm convinced that it would be good to be able to test with this sooner rather than later. 

If this looks good while testing, we can also help to get a stable release - we're at beta-9 https://www.drupal.org/project/layout_paragraphs/releases/2.0.0-beta9 so things have been moving ahead on that front.

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox want to take a look?

I wonder if schema changes will mean that default content needs creating against the version of layout_paragraphs installed?

**Comment by stephen-cox** [comment]
Having tested this, there are some minor changes to the default content, so this will need re-exporting after the update.

Layout Paragraphs 2 seems to work okay. I did come across some weirdness when creating a microsite with the node clone not working for all paragraph types, but I haven't been able to reliably reproduce the issue. There is an issue describing some issue with node cloning: https://www.drupal.org/project/layout_paragraphs/issues/3218226

Personally, I feel it's too close to user testing to make the change now. We don't have enough time to fully test it ourselves and so should be done in a more considered way, fixing the breaking tests in Subsites at the same time.

**Comment by finnlewis** [comment]
@stephen-cox I've fixed the tests on https://github.com/localgovdrupal/localgov_subsites/pull/85 

Maybe we can test with the node cloning and see if it works.

If not, we could look at the patch on https://www.drupal.org/project/layout_paragraphs/issues/3218226

**Comment by finnlewis** [comment]
I just did another test of the microsite creation process with layout_paragraphs 2.x and it all seems to work pretty nicely for me.

The node/1 gets cloned each time to node/2 node/3 etc and I can edit each paragraph without affecting the source node and paragraphs. 

I think we should test this on our users, this is the perfect time to test it. And layout_paragraphs 2.x is clearly the future! There is no more feature development on the 1.0.0 branch, 

If anyone else wants to test this PR further (@msayoung @markconroy @ekes ?), we have a branch on the localgov_microsites_project that pulls in the correct branches of the profile and localgov_page and localgov_subsites: 

https://github.com/localgovdrupal/localgov_microsites_project/tree/feature/84-layout-paragraphs-2

Or you can change your root composer.json to require: 

```
"localgovdrupal/localgov_microsites": "dev-feature/84-layout-paragraphs-2"
```

And run a `lando composer update -W`

What do you think @stephen-cox ? Worth a try?

**Comment by msayoung** [comment]
Very quick test. It certainly looks nicer and makes more visual sense. 

I don't think its great for keyboard accessibility, but I haven't done thorough testing. 

I also haven't tested the current interface, so I can't say which is better.

**Comment by finnlewis** [comment]
Converting this to draft until we're decided on this.

**Comment by finnlewis** [comment]
To proceed with this we need to sort out the dependency chain with localgov_paragraphs and localgov_page - making sure that layout_paragraphs is required in the correct composer.json, and ideally only one!

**Comment by markconroy** [comment]
I _think_ this can be closed as we have Layout Paragraphs 2 installed in Microsites already.

**Comment by finnlewis** [comment]
Yup, thanks all, this has been dealt with :)

**Pull request closed without merging**
