### PR TITLE
Restrict the version of drupal/core to 9.4.x but not up to 9.5, so th…

### PR DESCRIPTION
**Pull request by finnlewis**
Restrict the version of drupal/core to 9.4.x but not up to 9.5, so that patches for 9.4 can be applied.

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox I might be getting into a bit of a pickle here, can you advise or help?

I do think we need to require a version of the localgov_microsites_project that restricts the drupal core version to 9.4, so see 
https://github.com/localgovdrupal/localgov_microsites_project/blob/2.0.x/composer.json#L25-L26

I am for now specifically requiring that branch on https://github.com/localgovdrupal/localgov_microsites/blob/2.0.x/.github/workflows/localgov_microsites.yml#L84

This now allows composer to crack on gathering requirements and the first part of the job appears to complete. 

But now, the subsequent jobs, Coding standards, Deprecated code and PHPUnit tests cannot find the ./html directory.

Any idea what I've missed or messed?

Cheers dude!

**Comment by stephen-cox** [comment]
@finnlewis I think I have unpickled the GitHub Actions in this PR

The matrix for tests needs to be the same (there might be a better way to specify these)

**Review by stephen-cox — APPROVED** [review]
Looks to be pinning Drupal to 9.4 :+1:

**Comment by finnlewis** [comment]
Thanks so much @stephen-cox !

**Pull request merged**
