### PR TITLE
Set a version in info.yml to avoid htmlspecialchars(): Passing null t…

### LINKED ISSUE #321: [3.x] bug Deprecated function: htmlspecialchars():
Fresh install of localgov_microsites, visit the Reports > Status report:

```

Error message
Deprecated function: htmlspecialchars(): Passing null to parameter localgovdrupal/localgov_microsites_group#1 ($string) of type string is deprecated in Drupal\Component\Utility\Html::escape() (line 424 of core/lib/Drupal/Component/Utility/Html.php).

Drupal\Component\Utility\Html::escape(NULL) (Line: 262)
Drupal\Component\Render\FormattableMarkup::placeholderEscape(NULL) (Line: 232)
Drupal\Component\Render\FormattableMarkup::placeholderFormat('%profile_name (%profile-%version)', Array) (Line: 195)
Drupal\Core\StringTranslation\TranslatableMarkup->render() (Line: 15)
Drupal\Core\StringTranslation\TranslatableMarkup->__toString() (Line: 93)
__TwigTemplate_9979073c39574402eb2828334f04732b->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('core/themes/claro/templates/status-report-grouped.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('status_report_grouped', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 79)
__TwigTemplate_c09e3785dabe9359f34eb70f53d460e0->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('core/themes/claro/templates/status-report-page.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('status_report_page', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

### PR DESCRIPTION
**Pull request by finnlewis**
…o parameter. Fixes #321

### CODE REVIEW

**Comment by finnlewis** [comment]
So this PR fixes that error, but creates another coding standards error: 

```
FILE: ...rofiles/contrib/localgov_microsites/localgov_microsites.info.yml
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | Remove "version" from the info file, it will be added
   |         | by drupal.org packaging automatically
----------------------------------------------------------------------
```

So I wonder if we should commit this for now to remove the error on fresh installs, which is putting off people who are testing the system.

Also, why is this not a problem on LocalGov Drupal proper? 

Any thoughts @msayoung @stephen-cox @ekes  ?

**Comment by msayoung** [comment]
Well, I confirm it suppresses the error.

**Review by stephen-cox — CHANGES_REQUESTED** [review]
This looks to be a core bug, so adding a version to the profile is not a good solution.

The latest patch on this issue seems to fix it https://www.drupal.org/project/drupal/issues/3255637

**Comment by finnlewis** [comment]
Discussing with @stephen-cox  - I think best to apply the patch to microsites for now to suppress the error.

**Comment by finnlewis** [comment]
@stephen-cox changed the PR to use the patch and remove the VERSION parameter.

**Review by msayoung — APPROVED** [review]

**Pull request merged**
