### PR TITLE
Add missing media dependencies 

### LINKED ISSUE #374: Site installs broken
From Slack https://localgovdrupal.slack.com/archives/C01SZ6G3A7P/p1679999260236419

Chris Gibson
  [11:27 AM](https://localgovdrupal.slack.com/archives/C01SZ6G3A7P/p1679999260236419)
I've just tried to create a fresh install but it's falling over after the 'drush si localgov_microsites' with the following error. Has anyone else experienced this?

```
In UnmetDependenciesException.php line 100:

  Configuration objects provided by <em class="placeholder">localgov_directories_promo_page</em> have unmet dependencies: <em class="placeholder">core.entity_view_display.node.localgov_d
  irectory_promo_page.teaser (image.style.square_large)</em>
```
Appears to be something in the 2.5.0 release of LocalGov Directories as rolling this back to 2.4.1 fixes it

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #374

### CODE REVIEW

**Comment by stephen-cox** [comment]
Hmmm ... test pass locally. In any case the PHPUnit failures are not related to this issue

**Comment by stephen-cox** [comment]
@finnlewis @ekes I think this is quite high priority as it's breaking site installs at the moment, so please have a look when you have a chance.

Fix for the failing test here https://github.com/localgovdrupal/localgov_microsites_group/issues/394

**Comment by finnlewis** [comment]
Thank you @stephen-cox  - I have been testing on and off today between other commitments.

Locally, when trying to do a fresh install on this branch, I get: 

> 
>  [error]  Error: Call to a member function setStatus() on null in localgov_microsites_group_term_ui_modules_installed() (line 24 of /app/web/modules/contrib/localgov_microsites_group/modules/localgov_microsites_group_term_ui/localgov_microsites_group_term_ui.module) #0 [internal function]: localgov_microsites_group_term_ui_modules_installed(Array, false)
> #1 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(426): call_user_func_array(Object(Closure), Array)
> #2 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(405): Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object(Closure), 'localgov_micros...')
> #3 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(433): Drupal\Core\Extension\ModuleHandler->invokeAllWith('modules_install...', Object(Closure))
> #4 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(381): Drupal\Core\Extension\ModuleHandler->invokeAll('modules_install...', Array)
> #5 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
> #6 /app/web/core/includes/install.core.inc(1893): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
> #7 /app/web/core/includes/batch.inc(295): _install_module_batch('localgov_micros...', 'LocalgGov Micro...', Array)
> #8 /app/web/core/includes/form.inc(955): _batch_process()
> #9 /app/web/core/includes/install.core.inc(653): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
> #10 /app/web/core/includes/install.core.inc(571): install_run_task(Array, Array)
> #11 /app/web/core/includes/install.core.inc(119): install_run_tasks(Array, Array)
> #12 /app/vendor/drush/drush/includes/drush.inc(129): install_drupal(Object(Composer\Autoload\ClassLoader), Array, Array)
> #13 /app/vendor/drush/drush/includes/drush.inc(113): drush_call_user_func_array('install_drupal', Array)
> #14 /app/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(152): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array, Array)
> #15 [internal function]: Drush\Commands\core\SiteInstallCommands->install('localgov_micros...', Array)
> #16 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #17 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #18 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #19 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #20 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #21 /app/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #22 /app/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #23 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #24 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #25 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
> #26 /app/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
> #27 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
> #28 /app/bin/drush(120): include('/app/vendor/dru...')
> #29 {main}.

**Review by finnlewis — APPROVED** [review]
Aha! 

Sorry, didn't spot the other PR https://github.com/localgovdrupal/localgov_microsites_group/pull/394 

I see that fixes the install and with this, everything works again!

Thanks again @stephen-cox , still rocking it!

**Comment by finnlewis** [comment]
let's get this merged and do a release tomorrow.

**Comment by ekes** [comment]
I notice these are in /install These aren't duplicates of media? So it won't suffer whatever the issue was with media itself that caused them to be in /optional?

**Comment by ekes** [comment]
Note we're already working in /install - question if this is generally a good idea to be checked. But pattern is there.

**Pull request merged**
