### PR TITLE
sets claro as admin theme

### LINKED ISSUE #179: Use Claro as admin theme
I like the idea of relying on core as much as possible and contrib as little as possible. I also find Gin as a theme moves quite fast and can break things - especially now if we are using a dev version of it.

I propose that we start using Claro while we are developing the microsites project to properly evaluate it and see after another sprint or two if it's good enough for our use case, or if we need to go back to using Gin.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #179

### CODE REVIEW

**Comment by msayoung** [comment]
How do people @stephen-cox @ekes @finnlewis feel about moving to Claro over Gin? 

My preference for Claro is to do with button tab order - the save button comes after the form fields on a node edit form for example. 

Also Claro is now stable, so that's cool.

**Comment by willguv** [comment]
@msayoung Gin seems to be well used now, so gets the thumbs up from me

The only problem I have is using it on a laptop screen - sometimes save button is obscured by the sidebar. Is this an issue for anyone else?

**Comment by ekes** [comment]
On the claro side it's simpler, and at least for the microsites it doesn't need deep admin integration as they only see the group admin pages and tabs we have produced.

**Comment by finnlewis** [comment]
I like Gin, but there are a couple of anoying things about it (save button, tab order, permanent sidebar). But I'd like to get them logged and look at helping to make Gin better either way. 

It might be interesting to do some AB testing at some point with some of our users. 

Easy enough to switch between them so not too bothered at this stage if people want to focus on Claro for now.

**Comment by markconroy** [comment]
I'd like us to use Claro for a sprint or two and see what we think of it, then move back to Gin if we decide it's a better admin theme.

**Review by finnlewis — APPROVED** [review]
Let's do it !

**Pull request merged**
