### PR TITLE
Fix for Deprecated function: Creation of dynamic property

### PR DESCRIPTION
**Pull request by AWearring**
Fixes issue https://github.com/localgovdrupal/localgov_microsites/issues/414

### CODE REVIEW

**Comment by stephen-cox** [comment]
Github tests aren't running as we're not testing against the 4.x branch yet. This is fixed with #418.

If tests are fixed once #418 is merged this is good to be merged

**Comment by finnlewis** [comment]
Note this is from https://www.drupal.org/project/autosave_form/issues/3355495

It would be good to include the issue number in the patch comment.

**Comment by finnlewis** [comment]
I'll test this today.

**Comment by finnlewis** [comment]
Aha! @ekes has just pointed out that the issue has a more up to date solution on the merge request: 

https://git.drupalcode.org/project/autosave_form/-/merge_requests/12/diffs#note_290984

So we don't really want to add the patch https://www.drupal.org/files/issues/2023-04-20/autosave_form-dynamic-property-deprecation.patch

So the changes we want are: https://git.drupalcode.org/project/autosave_form/-/merge_requests/12.patch

BUT it is not safe to create a patch from a merge request diff, as the merge request might  change.

So we could create a patch file on the issue from the changes in that merge request.

Or we could encourage a new release (or both).

**Comment by finnlewis** [comment]
@AWearring I've updated the patch to one that is the same as the merge request on [that issue](https://www.drupal.org/project/autosave_form/issues/3355495).

Are you able to test if this works for you?

**Comment by AWearring** [comment]
@finnlewis I've built a fresh test controller site locally using this patch and I don't get the depreciation error, so it appears all good

**Comment by ekes** [comment]
Can I propose we merge this one. Get the one on microsite groups merged and then continue to tidy anything else that's failing in another issue/MR.

**Pull request merged**
